In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dim_customer = pd.read_csv(r"C:\Users\dell\Downloads\rpc_18_inputs_for_participant\rpc_18_inputs_for_participants\rpc_18_inputs_for_participants\RPC_18_Datasets\dim_customer.csv")
dim_delivery_partner = pd.read_csv(r"C:\Users\dell\Downloads\rpc_18_inputs_for_participant\rpc_18_inputs_for_participants\rpc_18_inputs_for_participants\RPC_18_Datasets\dim_delivery_partner_.csv")
dim_menu_item = pd.read_csv(r"C:\Users\dell\Downloads\rpc_18_inputs_for_participant\rpc_18_inputs_for_participants\rpc_18_inputs_for_participants\RPC_18_Datasets\dim_menu_item.csv")
dim_restaurant = pd.read_csv(r"C:\Users\dell\Downloads\rpc_18_inputs_for_participant\rpc_18_inputs_for_participants\rpc_18_inputs_for_participants\RPC_18_Datasets\dim_restaurant.csv")
fact_delivery_performance = pd.read_csv(r"C:\Users\dell\Downloads\rpc_18_inputs_for_participant\rpc_18_inputs_for_participants\rpc_18_inputs_for_participants\RPC_18_Datasets\fact_delivery_performance.csv")
fact_order_items = pd.read_csv(r"C:\Users\dell\Downloads\rpc_18_inputs_for_participant\rpc_18_inputs_for_participants\rpc_18_inputs_for_participants\RPC_18_Datasets\fact_order_items.csv")
fact_orders = pd.read_csv(r"C:\Users\dell\Downloads\rpc_18_inputs_for_participant\rpc_18_inputs_for_participants\rpc_18_inputs_for_participants\RPC_18_Datasets\fact_orders.csv")
fact_ratings = pd.read_csv(r"C:\Users\dell\Downloads\rpc_18_inputs_for_participant\rpc_18_inputs_for_participants\rpc_18_inputs_for_participants\RPC_18_Datasets\fact_ratings.csv")

In [3]:
dim_customer.head()
dim_menu_item.head()
dim_restaurant.head()
fact_delivery_performance.head()

,order_id,actual_delivery_time_mins,expected_delivery_time_mins,distance_km
0,ORD202501023439,31,31,6.4
1,ORD202501012051,46,42,1.9
2,ORD202501019281,25,31,6.2
3,ORD202501000124,29,41,6.2
4,ORD202501006518,37,41,2.4

In [4]:
tables = {
    "dim_customer": dim_customer,
    "dim_delivery_partner": dim_delivery_partner,
    "dim_menu_item": dim_menu_item,
    "dim_restaurant": dim_restaurant,
    "fact_delivery_performance": fact_delivery_performance,
    "fact_order_items": fact_order_items,
    "fact_orders": fact_orders,
    "fact_ratings": fact_ratings}
for name, df in tables.items():

    print("\n" + "="*80)
    print(f"TABLE : {name}")
    print("="*80)
    print("\n Shape")
    print("-"*80)
    print(f"Rows    : {df.shape[0]}")
    print(f"Columns : {df.shape[1]}")
    print("\n First 5 Rows")
    print("-"*80)
    print(df.head())
    print("\n Data Types & Info")
    print("-"*80)
    df.info()
    print("\n Null Values")
    print("-"*80)
    print(df.isnull().sum())
    print(f"\nTotal Null Values : {df.isnull().sum().sum()}")
    print("\n Duplicate Rows")
    print("-"*80)
    print(df.duplicated().sum())
    print("\n Unique Values")
    print("-"*80)
    print(df.nunique())
    cat_cols = df.select_dtypes(include=["object", "string"])
    print("\n Categorical Summary")
    print("-"*80)
    if not cat_cols.empty:
        print(cat_cols.describe().to_string())
    else:
        print("No categorical columns found")
    num_cols = df.select_dtypes(include="number")
    print("\n Numerical Summary")
    print("-"*80)
    if not num_cols.empty:
        print(num_cols.describe().to_string())
    else:
        print("No numerical columns found")

================================================================================
TABLE : dim_customer
================================================================================

 Shape
--------------------------------------------------------------------------------
Rows    : 107776
Columns : 4

 First 5 Rows
--------------------------------------------------------------------------------
  customer_id signup_date       city acquisition_channel
0  CUST000007  21-03-2025       Pune             Organic
1  CUST000008  07-02-2025    Kolkata            Referral
2  CUST000009  25-02-2025      Delhi                Paid
3  CUST000010  28-01-2025  Hyderabad                Paid
4  CUST000011  18-01-2025    Kolkata             Organic

 Data Types & Info
--------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 107776 entries, 0 to 107775
Data columns (total 4 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          107776 non-null  str
 1   signup_date          107776 non-null  str
 2   city                 107776 non-null  str
 3   acquisition_channel  107776 non-null  str
dtypes: str(4)
memory usage: 3.3 MB

 Null Values
--------------------------------------------------------------------------------
customer_id            0
signup_date            0
city                   0
acquisition_channel    0
dtype: int64

Total Null Values : 0

 Duplicate Rows
--------------------------------------------------------------------------------
0

 Unique Values
--------------------------------------------------------------------------------
customer_id            107776
signup_date               333
city                        8
acquisition_channel         4
dtype: int64

 Categorical Summary
--------------------------------------------------------------------------------
       customer_id signup_date       city acquisition_channel
count       107776      107776     107776              107776
unique      107776         333          8                   4
top     CUST000007  31-12-2024  Bengaluru             Organic
freq             1         736      30281               55382

 Numerical Summary
--------------------------------------------------------------------------------
No numerical columns found

================================================================================
TABLE : dim_delivery_partner
================================================================================

 Shape
--------------------------------------------------------------------------------
Rows    : 15000
Columns : 7

 First 5 Rows
--------------------------------------------------------------------------------
  delivery_partner_id partner_name       city vehicle_type employment_type  \
0             DP09615       Neha E  Bengaluru      Scooter       Full-time
1             DP02021       Neha V  Bengaluru         Bike       Full-time
2             DP05541      Vikas S      Delhi        Cycle       Part-time
3             DP13859       Amit B      Delhi        Cycle       Part-time
4             DP08091      Arjun R     Mumbai          Car       Full-time

   avg_rating is_active
0        3.77         Y
1        3.90         Y
2        3.33         Y
3        4.07         N
4        4.63         Y

 Data Types & Info
--------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_partner_id  15000 non-null  str
 1   partner_name         15000 non-null  str
 2   city                 15000 non-null  str
 3   vehicle_type         15000 non-null  str
 4   employment_type      15000 non-null  str
 5   avg_rating           15000 non-null  float64
 6   is_active            15000 non-null  str
dtypes: float64(1), str(6)
memory usage: 820.4 KB

 Null Values
--------------------------------------------------------------------------------
delivery_partner_id    0
partner_name           0
city                   0
vehicle_type           0
employment_type        0
avg_rating             0
is_active              0
dtype: int64

Total Null Values : 0

 Duplicate Rows
--------------------------------------------------------------------------------
0

 Unique Values
--------------------------------------------------------------------------------
delivery_partner_id    15000
partner_name             520
city                       8
vehicle_type               4
employment_type            3
avg_rating               184
is_active                  2
dtype: int64

 Categorical Summary
--------------------------------------------------------------------------------
       delivery_partner_id partner_name       city vehicle_type employment_type is_active
count                15000        15000      15000        15000           15000     15000
unique               15000          520          8            4               3         2
top                DP09615      Vikas C  Bengaluru      Scooter       Full-time         Y
freq                     1           51       3775         6011            7604     13235

 Numerical Summary
--------------------------------------------------------------------------------
         avg_rating
count  15000.000000
mean       4.197549
std        0.300532
min        3.060000
25%        3.990000
50%        4.200000
75%        4.400000
max        5.000000

================================================================================
TABLE : dim_menu_item
================================================================================

 Shape
--------------------------------------------------------------------------------
Rows    : 342671
Columns : 6

 First 5 Rows
--------------------------------------------------------------------------------
     menu_item_id restaurant_id           item_name    category is_veg   price
0  MENU12962_3216     REST12962  Paneer Tikka Pizza       Pizza      Y  271.05
1  MENU12962_1962     REST12962     Pepperoni Pizza       Pizza      N  327.26
2  MENU14069_0510     REST14069      Egg Fried Rice  Fried Rice      N  200.01
3  MENU14069_4308     REST14069        Paneer Tikka    Starters      Y  198.83
4  MENU08622_7574     REST08622        Kadai Paneer     Curries      Y  271.60

 Data Types & Info
--------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 342671 entries, 0 to 342670
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   menu_item_id   342671 non-null  str
 1   restaurant_id  342671 non-null  str
 2   item_name      342671 non-null  str
 3   category       342671 non-null  str
 4   is_veg         342671 non-null  str
 5   price          342671 non-null  float64
dtypes: float64(1), str(5)
memory usage: 15.7 MB

 Null Values
--------------------------------------------------------------------------------
menu_item_id     0
restaurant_id    0
item_name        0
category         0
is_veg           0
price            0
dtype: int64

Total Null Values : 0

 Duplicate Rows
--------------------------------------------------------------------------------
0

 Unique Values
--------------------------------------------------------------------------------
menu_item_id     342671
restaurant_id     19991
item_name            75
category             20
is_veg                2
price             34305
dtype: int64

 Categorical Summary
--------------------------------------------------------------------------------
          menu_item_id restaurant_id    item_name   category  is_veg
count           342671        342671       342671     342671  342671
unique          342671         19991           75         20       2
top     MENU12962_3216     REST11216  Sweet Lassi  Beverages       Y
freq                 1            49        23703      54390  225628

 Numerical Summary
--------------------------------------------------------------------------------
               price
count  342671.000000
mean      164.332567
std        69.083017
min        25.000000
25%       114.980000
50%       157.340000
75%       207.200000
max       449.990000

================================================================================
TABLE : dim_restaurant
================================================================================

 Shape
--------------------------------------------------------------------------------
Rows    : 19995
Columns : 7

 First 5 Rows
--------------------------------------------------------------------------------
  restaurant_id            restaurant_name       city  cuisine_type  \
0     REST12962  Flavours of Sweets Palace  Bengaluru       Chinese
1     REST14069       Royal Biryani Darbar  Ahmedabad     Fast Food
2     REST08622          Spicy Wraps Point     Mumbai  North Indian
3     REST19745       Delhi Express Palace  Ahmedabad         Pizza
4     REST02383         Namma Mess Delight     Mumbai       Healthy

    partner_type avg_prep_time_min is_active
0     Restaurant             26-40         N
1     Restaurant             16-25         Y
2     Restaurant             16-25         Y
3  Cloud Kitchen             16-25         Y
4     Restaurant             26-40         Y

 Data Types & Info
--------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 19995 entries, 0 to 19994
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   restaurant_id      19995 non-null  str
 1   restaurant_name    19995 non-null  str
 2   city               19995 non-null  str
 3   cuisine_type       19995 non-null  str
 4   partner_type       19995 non-null  str
 5   avg_prep_time_min  19995 non-null  str
 6   is_active          19995 non-null  str
dtypes: str(7)
memory usage: 1.1 MB

 Null Values
--------------------------------------------------------------------------------
restaurant_id        0
restaurant_name      0
city                 0
cuisine_type         0
partner_type         0
avg_prep_time_min    0
is_active            0
dtype: int64

Total Null Values : 0

 Duplicate Rows
--------------------------------------------------------------------------------
0

 Unique Values
--------------------------------------------------------------------------------
restaurant_id        19995
restaurant_name       4779
city                     8
cuisine_type             8
partner_type             2
avg_prep_time_min        4
is_active                2
dtype: int64

 Categorical Summary
--------------------------------------------------------------------------------
       restaurant_id          restaurant_name       city  cuisine_type partner_type avg_prep_time_min is_active
count          19995                    19995      19995         19995        19995             19995     19995
unique         19995                     4779          8             8            2                 4         2
top        REST12962  Punjabi Express Central  Bengaluru  North Indian   Restaurant             16-25         Y
freq               1                       12       4963          3942        14028              7987     18050

 Numerical Summary
--------------------------------------------------------------------------------
No numerical columns found

================================================================================
TABLE : fact_delivery_performance
================================================================================

 Shape
--------------------------------------------------------------------------------
Rows    : 149166
Columns : 4

 First 5 Rows
--------------------------------------------------------------------------------
          order_id  actual_delivery_time_mins  expected_delivery_time_mins  \
0  ORD202501023439                         31                           31
1  ORD202501012051                         46                           42
2  ORD202501019281                         25                           31
3  ORD202501000124                         29                           41
4  ORD202501006518                         37                           41

   distance_km
0          6.4
1          1.9
2          6.2
3          6.2
4          2.4

 Data Types & Info
--------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 149166 entries, 0 to 149165
Data columns (total 4 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   order_id                     149166 non-null  str
 1   actual_delivery_time_mins    149166 non-null  int64
 2   expected_delivery_time_mins  149166 non-null  int64
 3   distance_km                  149166 non-null  float64
dtypes: float64(1), int64(2), str(1)
memory usage: 4.6 MB

 Null Values
--------------------------------------------------------------------------------
order_id                       0
actual_delivery_time_mins      0
expected_delivery_time_mins    0
distance_km                    0
dtype: int64

Total Null Values : 0

 Duplicate Rows
--------------------------------------------------------------------------------
0

 Unique Values
--------------------------------------------------------------------------------
order_id                       149166
actual_delivery_time_mins          66
expected_delivery_time_mins        21
distance_km                        71
dtype: int64

 Categorical Summary
--------------------------------------------------------------------------------
               order_id
count            149166
unique           149166
top     ORD202501023439
freq                  1

 Numerical Summary
--------------------------------------------------------------------------------
       actual_delivery_time_mins  expected_delivery_time_mins    distance_km
count              149166.000000                149166.000000  149166.000000
mean                   44.404549                    38.691679       4.494667
std                    12.784224                     5.074100       2.021213
min                    25.000000                    30.000000       1.000000
25%                    36.000000                    35.000000       2.700000
50%                    42.000000                    39.000000       4.500000
75%                    50.000000                    43.000000       6.200000
max                    90.000000                    50.000000       8.000000

================================================================================
TABLE : fact_order_items
================================================================================

 Shape
--------------------------------------------------------------------------------
Rows    : 342994
Columns : 8

 First 5 Rows
--------------------------------------------------------------------------------
          order_id  item_id    menu_item_id restaurant_id  quantity  \
0  ORD202501006518  ITEM001  MENU12962_3216     REST12962         2
1  ORD202501006518  ITEM002  MENU12962_1962     REST12962         3
2  ORD202501019281  ITEM001  MENU14069_0510     REST14069         2
3  ORD202501019281  ITEM002  MENU14069_4308     REST14069         3
4  ORD202501023439  ITEM001  MENU08622_7574     REST08622         2

   unit_price  item_discount  line_total
0       48.31           0.00       96.62
1       61.24           0.00      183.71
2       87.19           0.00      174.38
3       84.67           0.00      254.00
4      235.81          35.44      436.18

 Data Types & Info
--------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 342994 entries, 0 to 342993
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       342994 non-null  str
 1   item_id        342994 non-null  str
 2   menu_item_id   342994 non-null  str
 3   restaurant_id  342994 non-null  str
 4   quantity       342994 non-null  int64
 5   unit_price     342994 non-null  float64
 6   item_discount  342994 non-null  float64
 7   line_total     342994 non-null  float64
dtypes: float64(3), int64(1), str(4)
memory usage: 20.9 MB

 Null Values
--------------------------------------------------------------------------------
order_id         0
item_id          0
menu_item_id     0
restaurant_id    0
quantity         0
unit_price       0
item_discount    0
line_total       0
dtype: int64

Total Null Values : 0

 Duplicate Rows
--------------------------------------------------------------------------------
0

 Unique Values
--------------------------------------------------------------------------------
order_id         154479
item_id               5
menu_item_id     342671
restaurant_id     19991
quantity              3
unit_price        34771
item_discount     10055
line_total        46191
dtype: int64

 Categorical Summary
--------------------------------------------------------------------------------
               order_id  item_id    menu_item_id restaurant_id
count            342994   342994          342994        342994
unique           154479        5          342671         19991
top     ORD202501003201  ITEM001  MENU12044_8764     REST11216
freq                  5   154479               2            49

 Numerical Summary
--------------------------------------------------------------------------------
            quantity     unit_price  item_discount     line_total
count  342994.000000  342994.000000  342994.000000  342994.000000
mean        1.998012      86.307888       9.193635     143.814273
std         0.818149      79.286627      17.089856     108.096155
min         1.000000       4.330000       0.000000       5.410000
25%         1.000000      39.350000       0.000000      66.340000
50%         2.000000      62.270000       0.000000     112.785000
75%         3.000000     102.230000      12.580000     190.150000
max         3.000000     900.000000     220.660000     900.000000

================================================================================
TABLE : fact_orders
================================================================================

 Shape
--------------------------------------------------------------------------------
Rows    : 149166
Columns : 11

 First 5 Rows
--------------------------------------------------------------------------------
          order_id customer_id restaurant_id delivery_partner_id  \
0  ORD202501023439  CUST181110     REST08622             DP05541
1  ORD202501012051  CUST025572     REST02383             DP08091
2  ORD202501019281  CUST179306     REST14069             DP02021
3  ORD202501000124  CUST191820     REST19745             DP13859
4  ORD202501006518  CUST033760     REST12962             DP09615

       order_timestamp  subtotal_amount  discount_amount  delivery_fee  \
0  2025-01-01 12:00:00           471.62            35.44         30.56
1  2025-01-01 12:00:00           255.68             0.00         27.45
2  2025-01-01 12:00:00           428.38             0.00         26.23
3  2025-01-01 12:00:00           260.81             0.00         32.75
4  2025-01-01 12:00:00           280.33             0.00         25.57

   total_amount is_cod is_cancelled
0        466.74      N            N
1        283.13      Y            N
2        454.61      N            N
3        293.56      N            N
4        305.90      N            N

 Data Types & Info
--------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 149166 entries, 0 to 149165
Data columns (total 11 columns):

In [5]:
dim_customer.signup_date = pd.to_datetime(dim_customer.signup_date,format='%d-%m-%Y').dt.date
dim_customer['city'] = dim_customer['city'].astype('category')
dim_customer['acquisition_channel'] = dim_customer['acquisition_channel'].astype('category')

In [6]:
dim_delivery_partner['city'] = dim_delivery_partner['city'].astype('category')
dim_delivery_partner['vehicle_type'] = dim_delivery_partner['vehicle_type'].astype('category')
dim_delivery_partner['employment_type']=dim_delivery_partner['employment_type'].astype('category')
dim_delivery_partner['is_active']=dim_delivery_partner['is_active'].astype('category')

In [7]:
dim_menu_item.dtypes
dim_menu_item['item_name']=dim_menu_item['item_name'].astype('category')
dim_menu_item['category']=dim_menu_item['category'].astype('category')
dim_menu_item['is_veg']=dim_menu_item['is_veg'].astype('category')

In [8]:
ls = ["city","cuisine_type","partner_type","avg_prep_time_min","is_active"]
for i in ls:
    dim_restaurant[i] = dim_restaurant[i].astype('category')

In [9]:
fact_order_items['item_id'] = fact_order_items['item_id'].astype('category')

In [ ]:
fact_orders['restaurant_id'] = fact_orders['restaurant_id'].astype('category')
fact_orders['is_cod'] = fact_orders['is_cod'].astype('category')
fact_orders['is_cancelled'] = fact_orders['is_cancelled'].astype('category')
fact_orders['order_timestamp'] = pd.to_datetime(fact_orders['order_timestamp'])

In [11]:
fact_ratings.drop_duplicates(inplace=True)

In [12]:
fact_ratings[fact_ratings['review_text'].isnull()]
fact_ratings=fact_ratings.dropna(subset='review_text').reset_index(drop=True)

In [13]:
fact_ratings['review_timestamp'] = pd.to_datetime(fact_ratings['review_timestamp'],dayfirst=True)

In [14]:
fact_ratings

,order_id,customer_id,restaurant_id,rating,review_text,review_timestamp,sentiment_score
0,ORD202501023439,CUST181110,REST08622,4.5,Super fast delivery,2025-01-01 15:00:00,0.75
1,ORD202501019281,CUST179306,REST14069,4.5,Great taste!,2025-01-01 15:00:00,0.75
2,ORD202501018036,CUST093042,REST13907,5.0,Super fast delivery,2025-01-01 14:03:00,1.00
3,ORD202501007724,CUST110825,REST08451,4.0,Tasty but a bit late,2025-01-01 14:06:00,0.50
4,ORD202501002349,CUST181669,REST00225,4.4,Satisfied overall,2025-01-01 14:06:00,0.70
...,...,...,...,...,...,...,...
68820,ORD202509009609,CUST057825,REST01490,2.2,Stale food served,2025-09-30 23:40:00,-0.40
68821,ORD202509004269,CUST114184,REST16601,3.6,Could be hotter,2025-09-30 23:41:00,0.30
68822,ORD202509006794,CUST173128,REST11207,1.2,Horrible service,2025-09-30 23:43:00,-0.90
68823,ORD202509008376,CUST135098,REST05223,2.1,Packaging issue,2025-09-30 23:57:00,-0.45
68824,ORD202509002465,CUST056144,REST19517,2.1,Food safety issue,2025-09-30 23:59:00,-0.45

In [ ]:
for name, df in tables.items():
    df.to_csv(f'C:\\Users\\dell\\Desktop\\Ongoing Projects\\{name}.csv')
    print(f'Dataframe {name} is successfully saved')

"for name, df in tables.items():\n    df.to_csv(f'C:\\Users\\dell\\Desktop\\Ongoing Projects\\{name}.csv')\n    print(f'Dataframe {name} is successfully saved')"

In [17]:
from sqlalchemy import create_engine,text

In [3]:
engine = create_engine(
    "mysql+pymysql://root:yash@localhost/analysis")

In [7]:
conn = engine.connect()

In [ ]:
tables = {
    "dim_customer": dim_customer,
    "dim_delivery_partner": dim_delivery_partner,
    "dim_menu_item": dim_menu_item,
    "dim_restaurant": dim_restaurant,
    "fact_delivery_performance": fact_delivery_performance.
    "fact_order_items": fact_order_items,
    "fact_orders": fact_orders,
    "fact_ratings": fact_ratings}

for table_name,df in tables.items():
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=30000,
        method='multi'
    )
    print(f"{table_name} imported")

fact_order_items imported
fact_orders imported
fact_ratings imported

In [19]:
result = conn.execute(
    text("SELECT * FROM dim_customer")
)

In [21]:
pd.DataFrame(result)

       customer_id signup_date       city acquisition_channel
0       CUST000007  2025-03-21       Pune             Organic
1       CUST000008  2025-02-07    Kolkata            Referral
2       CUST000009  2025-02-25      Delhi                Paid
3       CUST000010  2025-01-28  Hyderabad                Paid
4       CUST000011  2025-01-18    Kolkata             Organic
...            ...         ...        ...                 ...
107771  CUST199995  2024-11-19      Delhi             Organic
107772  CUST199996  2025-01-14  Hyderabad              Social
107773  CUST199997  2024-12-22  Hyderabad             Organic
107774  CUST199999  2025-05-11     Mumbai             Organic
107775  CUST200000  2025-02-25    Chennai             Organic

[107776 rows x 4 columns]